update tests to fail on entrypoint and save test_result.txt as artifact

diff --git a/.github/workflows/build-test-push.yml b/.github/workflows/build-test-push.yml
--- a/.github/workflows/build-test-push.yml
+++ b/.github/workflows/build-test-push.yml
@@ -20,14 +20,14 @@ jobs:
         run: |
           docker build --build-arg GITHUB_SHA=${{ github.sha }} -t ${{ env.DOCKER_TAG }} -f ./.github/workflows/build-test-push/Dockerfile .
           docker run --name run_tests bigomics/omicsplayground:latest
-          docker cp run_tests:omicsplayground/tests .
+          docker cp run_tests:/test_result.txt .
       - 
-        name: Upload snapshots as artifact
+        name: Upload error log
         if: always()
         uses: actions/upload-artifact@v3
         with:
-          name: testthat-snapshots
-          path: ./tests/*
+          name: test-error-log
+          path: ./test_result.txt
           if-no-files-found: ignore
       - 
         name: Setup upterm session
@@ -38,10 +38,10 @@ jobs:
           ## limits ssh access and adds the ssh public keys of the listed GitHub users
           limit-access-to-users: mauromiguelm
           wait-timeout-minutes: 120
-      -
-        name: Fail GHA if snapshot test failed
-        if: always()
-        run: |
-          if [[ "${{ steps.test-snapshot.outputs.test_result }}" == "FALSE" ]]; then
-            exit 1
-          fi 
+      # -
+      #   name: Fail GHA if snapshot test failed
+      #   if: always()
+      #   run: |
+      #     if [[ "${{ steps.test-snapshot.outputs.test_result }}" == "FALSE" ]]; then
+      #       exit 1
+      #     fi 
